import = [
  "~/.config/catppuccin-mocha.toml"
]

[window]
padding = { x = 15, y = 15}
opacity = 0.8
blur = true

[font]
size = 22.0
normal = { family = "Iosevka Term", style = "Regular"}
bold = { family = "Iosevka Term", style = "Bold"}
italic = { family = "Iosevka Term", style = "Italic"}
bold_italic = { family = "Iosevka Term", style = "Bold Italic"}

[env]
TERM = "xterm-256color"
